### PR TITLE
Upgrade to 3.0.12

### PR DESCRIPTION
**Pull request by nicoddemus**
Closes #14, Closes #13

### CODE REVIEW

**Comment by nicoddemus** [comment]
@conda-forge/filelock ready for review. 👍

**Comment by jakirkham** [comment]
Thanks Bruno! 😄 Would you like to add yourself as a maintainer here?

**Comment by nicoddemus** [comment]
My pleasure!

Sure, added myself as maintainer.

**Comment by jakirkham** [comment]
Thank you! 😀

**Pull request merged**
